version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache

  redis:
    container_name: redis-srv
    image: redis  
    ports:
      - "8081:6379"
    restart: always
    volumes:
     - ./redis-data:/data

  # web:
  #   build:
  #     dockerfile: Dockerfile-alpine
  #     context: ./web
  #   ports:
  #     - 8081:80
  #   depends_on:
  #     - redis
